# Default values for register-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: ""
  pullPolicy: IfNotPresent

time: 0
service:
  name: ""
config:
  port: 8080


env:
  open:
    SPRING_PROFILES_ACTIVE: dev
    JAVA_TOOL_OPTIONS: -XX:ActiveProcessorCount=2  -XX:-OmitStackTraceInFastThrow   -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMPercentage=80.0 -XX:InitialRAMPercentage=30.0 -XX:MinRAMPercentage=30.0

monitor:
  enable: true
resource:
  enable: true
resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources,such as Minikube. If you do want to specify resources,uncomment the following
  # lines,adjust them as necessary,and remove the curly braces after 'resources:'.
  limits:
     cpu: 0.5
     memory: 2048Mi
  requests:
     cpu: 0.1
     memory: 256Mi


