apiVersion: v1
kind: Service
metadata: 
    name: {{ .Values.service.name }}
    labels:
       name: {{ .Values.service.name }}
    namespace: {{ .Release.Namespace }}
spec: 
    type: ClusterIP
    ports:
      - port: {{ .Values.config.port }}
        targetPort: {{ .Values.config.port }}
        protocol: TCP
    selector:
{{ include "service.labels.standard" . | indent 6 }}
